# Generated by Django 3.2.9 on 2021-11-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=10)),
                ('link', models.FilePathField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
